<?php

namespace TurhanOz\DragDropBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MechanicalPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MechanicalPartRepository extends EntityRepository
{
}
